import turtle
Tuan_Scr = turtle.Screen()
Tuan_br = turtle.Turtle()
turtle.bgcolor("pink")
Tuan_br.speed(1)
Tuan_br.pencolor("blue")
Tuan_br.fillcolor("red")
Tuan_br.begin_fill()
for i in range(4):
  Tuan_br.forward(300)
  Tuan_br.right(90)
Tuan_br.end_fill()
Tuan_br.penup()
Tuan_br.goto(150,60)
Tuan_br.pendown()
Tuan_br.fillcolor("purple")
Tuan_br.begin_fill()
Tuan_br.circle(150)
Tuan_br.end_fill()
Tuan_br.right(90)
Tuan_br.goto(100,100)

